name: DOC

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate_and_publish_documentation:
    name: Generate and Publish Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Pages 📄
        uses: actions/configure-pages@v2

      - name: Setup Graphviz 📈
        uses: ts-graphviz/setup-graphviz@v1

      - name: Render .drawio Files 🖼️
        uses: rlespinasse/drawio-export-action@v2
        with:
            format: png
            path: docs/assets
            output: .
            action-mode: all
            remove-page-suffix: true

      - name: Prepare Documentation Build 🏗️
        run: |
          wget -O theme.zip $(curl -s 'https://api.github.com/repos/jothepro/doxygen-awesome-css/releases/latest' | grep zipball_url | cut -d '"' -f 4 -z)
          unzip -j -d build/docs/theme theme.zip '*.js' '*.css'

      - name: Build Docs with Doxygen 📙
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
            doxyfile-path: docs/Doxyfile

      - name: NoJekyll ❌
        run: touch docs/html/.nojekyll

      - name: Upload Artifact 🏺
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/html/

      - name: Deploy to GitHub Pages 🚀
        uses: actions/deploy-pages@v1
