name: TEST

on:
  push:

jobs:
  test_mushlib:
    name: Run MushLib Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup NASM 🕸️
        uses: ilammy/setup-nasm@v1

      - name: Setup GCC 🐃
        uses: egor-tensin/setup-gcc@v1
        with:
          cc: 1

      - name: Setup GCC Multilib 🗂️
        run: sudo apt-get install -y gcc-multilib

      - name: Setup Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Setup CMake 📐
        uses: jwlawson/actions-setup-cmake@v1.13

      - name: Test 🧪
        run: make test
